name: Run ESLint on Push and Pull Requests
on:
    push:
      branches:
        - main
        - develop
    pull_request:
      branches:
        - main
        - develop
    
jobs:
  build:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.17.0
      - name: Run Linters for frontend
        run: npm install && npm run lint
        working-directory: src/frontend
      - name: Run Linters for api-gateway
        run: npm install && npm run lint
        working-directory: src/api-gateway
