name: Update codecov
on:
  push:
    branches: [ main, develop , test ]

  pull_request:
    branches: [ main, develop , test ]

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

#      - name: Install dependencies
#        run: npm install && npm run test:cov
#        working-directory: src/frontend

      - name: Run api tests and collect coverage
        run: npm install && npm run test:cov
        working-directory: src/api-gateway/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
